import type {
  Repository,
  Developer,
  ChatMessage,
  KnowledgeNode,
  KnowledgeEdge,
  DocEntry,
  SearchResult,
} from "./types";

export const currentUser: Developer = {
  id: "u-001",
  name: "Chunduru Sai",
  handle: "sai.chunduru",
  role: "ADMIN",
  avatar: "CS",
  tenure: "4y 2m",
  active: true,
  expertise: 92,
  commits: 2148,
  reviews: 812,
  topLanguages: [
    { name: "Java", pct: 46 },
    { name: "TypeScript", pct: 24 },
    { name: "Python", pct: 14 },
    { name: "Go", pct: 10 },
    { name: "SQL", pct: 6 },
  ],
  skills: [
    { name: "System Design", score: 94 },
    { name: "Spring Boot", score: 96 },
    { name: "Distributed Systems", score: 88 },
    { name: "AI / RAG", score: 82 },
    { name: "DevOps", score: 76 },
    { name: "Security", score: 84 },
  ],
  codingStyle: {
    avgPrSize: 312,
    avgReviewTimeMin: 38,
    testCoverage: 87,
    docComments: 74,
  },
};

export const repositories: Repository[] = [
  {
    id: "r-01",
    name: "payment-gateway",
    org: "acme-fintech",
    language: "Java",
    stars: 184,
    commitsLast90: 412,
    contributors: 9,
    lastCommit: "2h ago",
    risk: "LOW",
    busFactor: 5,
    knowledgeScore: 91,
  },
  {
    id: "r-02",
    name: "identity-service",
    org: "acme-fintech",
    language: "Java",
    stars: 96,
    commitsLast90: 187,
    contributors: 4,
    lastCommit: "5h ago",
    risk: "MEDIUM",
    busFactor: 2,
    knowledgeScore: 74,
  },
  {
    id: "r-03",
    name: "ledger-core",
    org: "acme-fintech",
    language: "Java",
    stars: 62,
    commitsLast90: 58,
    contributors: 1,
    lastCommit: "23d ago",
    risk: "CRITICAL",
    busFactor: 1,
    knowledgeScore: 38,
  },
  {
    id: "r-04",
    name: "fraud-detector",
    org: "acme-fintech",
    language: "Python",
    stars: 141,
    commitsLast90: 264,
    contributors: 6,
    lastCommit: "1d ago",
    risk: "LOW",
    busFactor: 4,
    knowledgeScore: 86,
  },
  {
    id: "r-05",
    name: "customer-portal",
    org: "acme-fintech",
    language: "TypeScript",
    stars: 52,
    commitsLast90: 301,
    contributors: 8,
    lastCommit: "4h ago",
    risk: "LOW",
    busFactor: 6,
    knowledgeScore: 88,
  },
  {
    id: "r-06",
    name: "kyc-pipeline",
    org: "acme-fintech",
    language: "Go",
    stars: 31,
    commitsLast90: 44,
    contributors: 2,
    lastCommit: "11d ago",
    risk: "HIGH",
    busFactor: 1,
    knowledgeScore: 52,
  },
  {
    id: "r-07",
    name: "notification-hub",
    org: "acme-fintech",
    language: "Java",
    stars: 27,
    commitsLast90: 119,
    contributors: 3,
    lastCommit: "2d ago",
    risk: "MEDIUM",
    busFactor: 2,
    knowledgeScore: 68,
  },
  {
    id: "r-08",
    name: "mobile-bff",
    org: "acme-fintech",
    language: "TypeScript",
    stars: 73,
    commitsLast90: 208,
    contributors: 5,
    lastCommit: "8h ago",
    risk: "LOW",
    busFactor: 4,
    knowledgeScore: 82,
  },
];

export const team: Developer[] = [
  currentUser,
  {
    id: "u-002",
    name: "Ananya Rao",
    handle: "ananya.rao",
    role: "TEAM_LEAD",
    avatar: "AR",
    tenure: "3y 6m",
    active: true,
    expertise: 88,
    commits: 1704,
    reviews: 921,
    topLanguages: [
      { name: "Java", pct: 58 },
      { name: "Kotlin", pct: 22 },
      { name: "SQL", pct: 12 },
      { name: "Bash", pct: 8 },
    ],
    skills: [
      { name: "System Design", score: 92 },
      { name: "Spring Boot", score: 94 },
      { name: "Kafka", score: 86 },
      { name: "Mentorship", score: 96 },
      { name: "Observability", score: 82 },
      { name: "SQL Tuning", score: 88 },
    ],
    codingStyle: { avgPrSize: 244, avgReviewTimeMin: 22, testCoverage: 92, docComments: 81 },
  },
  {
    id: "u-003",
    name: "Rahul Verma",
    handle: "rahul.verma",
    role: "DEVELOPER",
    avatar: "RV",
    tenure: "2y 1m",
    active: true,
    expertise: 79,
    commits: 986,
    reviews: 412,
    topLanguages: [
      { name: "TypeScript", pct: 62 },
      { name: "React", pct: 22 },
      { name: "Node.js", pct: 10 },
      { name: "CSS", pct: 6 },
    ],
    skills: [
      { name: "React", score: 92 },
      { name: "TypeScript", score: 94 },
      { name: "Design Systems", score: 86 },
      { name: "Accessibility", score: 80 },
      { name: "Testing", score: 78 },
      { name: "Performance", score: 82 },
    ],
    codingStyle: { avgPrSize: 198, avgReviewTimeMin: 31, testCoverage: 84, docComments: 66 },
  },
  {
    id: "u-004",
    name: "Priya Nair",
    handle: "priya.nair",
    role: "DEVELOPER",
    avatar: "PN",
    tenure: "—",
    active: false,
    expertise: 84,
    commits: 1238,
    reviews: 547,
    topLanguages: [
      { name: "Java", pct: 72 },
      { name: "SQL", pct: 16 },
      { name: "Python", pct: 12 },
    ],
    skills: [
      { name: "Spring Boot", score: 92 },
      { name: "PostgreSQL", score: 90 },
      { name: "Domain Modeling", score: 88 },
      { name: "Legacy Systems", score: 94 },
      { name: "Performance", score: 82 },
      { name: "Mentorship", score: 78 },
    ],
    codingStyle: { avgPrSize: 284, avgReviewTimeMin: 46, testCoverage: 78, docComments: 72 },
  },
  {
    id: "u-005",
    name: "Arjun Mehta",
    handle: "arjun.mehta",
    role: "DEVELOPER",
    avatar: "AM",
    tenure: "1y 4m",
    active: true,
    expertise: 71,
    commits: 612,
    reviews: 188,
    topLanguages: [
      { name: "Python", pct: 54 },
      { name: "Java", pct: 28 },
      { name: "SQL", pct: 12 },
      { name: "Shell", pct: 6 },
    ],
    skills: [
      { name: "ML Ops", score: 86 },
      { name: "Python", score: 90 },
      { name: "Kubernetes", score: 78 },
      { name: "Observability", score: 72 },
      { name: "CI/CD", score: 80 },
      { name: "Cloud", score: 76 },
    ],
    codingStyle: { avgPrSize: 412, avgReviewTimeMin: 54, testCoverage: 68, docComments: 58 },
  },
];

export const seedConversation: ChatMessage[] = [
  {
    id: "m-1",
    role: "user",
    content: "Why was Redis introduced into the payment-gateway in Q3 2024?",
    timestamp: "Today, 09:41",
  },
  {
    id: "m-2",
    role: "assistant",
    content:
      "Redis was introduced to offload the idempotency-key lookup path from PostgreSQL. Priya Nair's PR #4812 (merged 2024-08-19) notes that p99 latency on `/v1/payments` dropped from 312ms to 84ms after the change, and the idempotency cache TTL was set to 24h to match the retry window. The trade-off documented in the PR review thread: eventual consistency on failover, mitigated by a Redis Sentinel cluster with quorum writes.",
    timestamp: "Today, 09:41",
    sources: [
      {
        repo: "acme-fintech/payment-gateway",
        commit: "8f2c1a4",
        author: "priya.nair",
        snippet: "feat(cache): add Redis-backed idempotency store for /v1/payments",
      },
      {
        repo: "acme-fintech/payment-gateway",
        commit: "31b9fe0",
        author: "ananya.rao",
        snippet: "ops: deploy Redis Sentinel with 3-node quorum",
      },
    ],
  },
];

export const knowledgeNodes: KnowledgeNode[] = [
  { id: "api", label: "API Gateway", type: "api", risk: 0.2, ownerCount: 5, x: 420, y: 80 },
  { id: "auth", label: "Identity", type: "service", risk: 0.45, ownerCount: 3, x: 180, y: 180 },
  { id: "pay", label: "Payments", type: "service", risk: 0.15, ownerCount: 6, x: 420, y: 220 },
  { id: "fraud", label: "Fraud ML", type: "service", risk: 0.3, ownerCount: 4, x: 660, y: 180 },
  { id: "ledger", label: "Ledger Core", type: "service", risk: 0.92, ownerCount: 1, x: 420, y: 380 },
  { id: "pg", label: "PostgreSQL", type: "db", risk: 0.2, ownerCount: 7, x: 260, y: 480 },
  { id: "redis", label: "Redis", type: "db", risk: 0.35, ownerCount: 4, x: 580, y: 480 },
  { id: "kafka", label: "Kafka", type: "queue", risk: 0.4, ownerCount: 3, x: 180, y: 340 },
  { id: "notif", label: "Notifications", type: "service", risk: 0.55, ownerCount: 2, x: 660, y: 340 },
  { id: "kyc", label: "KYC Pipeline", type: "service", risk: 0.78, ownerCount: 1, x: 780, y: 240 },
];

export const knowledgeEdges: KnowledgeEdge[] = [
  { from: "api", to: "auth", weight: 3 },
  { from: "api", to: "pay", weight: 5 },
  { from: "api", to: "fraud", weight: 2 },
  { from: "pay", to: "ledger", weight: 5 },
  { from: "pay", to: "pg", weight: 4 },
  { from: "pay", to: "redis", weight: 3 },
  { from: "pay", to: "kafka", weight: 3 },
  { from: "fraud", to: "kafka", weight: 2 },
  { from: "notif", to: "kafka", weight: 2 },
  { from: "fraud", to: "redis", weight: 2 },
  { from: "ledger", to: "pg", weight: 5 },
  { from: "auth", to: "pg", weight: 3 },
  { from: "api", to: "kyc", weight: 1 },
  { from: "kyc", to: "pg", weight: 2 },
];

export const docs: DocEntry[] = [
  {
    id: "d-01",
    title: "Payment Idempotency Contract",
    module: "payment-gateway",
    generatedAt: "2h ago",
    coverage: 94,
    summary:
      "Documents the Idempotency-Key header contract, retry semantics, 24h TTL, and Redis failure modes.",
  },
  {
    id: "d-02",
    title: "Ledger Double-Entry Invariant",
    module: "ledger-core",
    generatedAt: "1d ago",
    coverage: 41,
    summary:
      "Partial. Inferred from commit history. Original author (priya.nair) departed; gaps in saga rollback path.",
  },
  {
    id: "d-03",
    title: "Kafka Topic Schema Registry",
    module: "notification-hub",
    generatedAt: "5h ago",
    coverage: 82,
    summary:
      "Auto-generated from Avro schemas and producer commits. Includes backward-compat matrix.",
  },
  {
    id: "d-04",
    title: "KYC State Machine",
    module: "kyc-pipeline",
    generatedAt: "11d ago",
    coverage: 58,
    summary:
      "States inferred from tests. Transition rules partially missing for `manual_review -> escalated`.",
  },
  {
    id: "d-05",
    title: "Auth Token Rotation",
    module: "identity-service",
    generatedAt: "3h ago",
    coverage: 88,
    summary:
      "Refresh token rotation, revocation list, cookie flags, and rotation-on-reuse detection.",
  },
];

export const searchResults: SearchResult[] = [
  {
    id: "s-1",
    title: "Why Redis Sentinel over Redis Cluster",
    source: "acme-fintech/payment-gateway",
    type: "pr",
    snippet:
      "Sentinel was chosen because our write path is single-master and we needed faster failover (<3s) without slot rebalancing complexity...",
    score: 0.94,
    author: "priya.nair",
    date: "2024-08-19",
  },
  {
    id: "s-2",
    title: "feat: idempotency-key lookup via Redis",
    source: "acme-fintech/payment-gateway",
    type: "commit",
    snippet: "Moves idempotency-key lookup from pg to redis. Fallback to pg on cache miss.",
    score: 0.91,
    author: "priya.nair",
    date: "2024-08-15",
  },
  {
    id: "s-3",
    title: "Ledger Core — Saga Rollback",
    source: "acme-fintech/ledger-core",
    type: "doc",
    snippet:
      "Auto-generated. Coverage 41%. Compensating transactions documented for 4 of 7 saga steps.",
    score: 0.78,
    author: "AI (twin)",
    date: "2025-01-12",
  },
  {
    id: "s-4",
    title: "IdempotencyService.java",
    source: "acme-fintech/payment-gateway",
    type: "code",
    snippet:
      "public class IdempotencyService { public Outcome process(String key, Payload p) { ... } }",
    score: 0.72,
    author: "ananya.rao",
    date: "2024-09-02",
  },
];

export const activitySeries = [
  { day: "Mon", commits: 42, reviews: 28, incidents: 0 },
  { day: "Tue", commits: 61, reviews: 34, incidents: 1 },
  { day: "Wed", commits: 54, reviews: 41, incidents: 0 },
  { day: "Thu", commits: 73, reviews: 38, incidents: 0 },
  { day: "Fri", commits: 68, reviews: 29, incidents: 2 },
  { day: "Sat", commits: 21, reviews: 8, incidents: 0 },
  { day: "Sun", commits: 14, reviews: 5, incidents: 0 },
];

export const knowledgeHealth = {
  overall: 74,
  documented: 68,
  busFactor: 62,
  freshness: 81,
  coverage: 77,
};

export const riskTrend = [
  { w: "W-8", score: 58 },
  { w: "W-7", score: 55 },
  { w: "W-6", score: 52 },
  { w: "W-5", score: 49 },
  { w: "W-4", score: 46 },
  { w: "W-3", score: 44 },
  { w: "W-2", score: 41 },
  { w: "W-1", score: 38 },
];

export const aiInsights = [
  {
    id: "i-1",
    severity: "CRITICAL" as const,
    title: "Single-owner service detected",
    body: "ledger-core has a bus factor of 1. Priya Nair (departed) authored 82% of its commits. Recommend pairing Arjun Mehta with Ananya Rao for a 2-week knowledge transfer sprint.",
    module: "ledger-core",
  },
  {
    id: "i-2",
    severity: "HIGH" as const,
    title: "Stale documentation drift",
    body: "kyc-pipeline docs are 11 days behind the latest commit. Auto-generator confidence dropped below 60%.",
    module: "kyc-pipeline",
  },
  {
    id: "i-3",
    severity: "MEDIUM" as const,
    title: "Review bottleneck",
    body: "Arjun Mehta's avg review wait is 54 min — 2.1× team median. Consider adding Rahul Verma as secondary reviewer.",
    module: "team",
  },
  {
    id: "i-4",
    severity: "LOW" as const,
    title: "New expertise emerging",
    body: "Rahul Verma has crossed 90% expertise in React/TypeScript. Consider nominating as frontend guild lead.",
    module: "team",
  },
];
